### ISSUE TITLE
Django: set default datetime values in db schema

### ISSUE THREAD

**Issue by radowit** [zagrajmy/zm-backend#20]

**Comment by radowit** [comment]
@hasparus 
I could easily add migration that will get the auto_now_add working on db level (for `created_at` fields), but automatically updating `updated_at` field would require creating a db function and trigger, which we want to avoid because it's a code which is hard to test and update.
What do you think if I get done the default value for datetime field, but leave updating `updated_at` field to frontend?

**Comment by hasparus** [comment]
sure
